repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: detect-private-key
      - id: check-yaml
        args:
          - --unsafe
        exclude: ^\.github/workflows/
      - id: check-toml
      - id: check-json
      - id: trailing-whitespace
        exclude: ^\.github/workflows/
      - id: end-of-file-fixer
        exclude: ^\.github/workflows/

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.19
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: system
        types: [python]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        require_serial: true
        language: system
        types: [python]

      - id: local-pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        always_run: true

      - id: local-commitizen
        name: commitizen check
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]

      # - id: local-commitizen-branch
      #   name: commitizen branch check
      #   entry: uv run cz check --rev-range
      #   language: system
      #   stages: [pre-push]
      #   pass_filenames: false
